---
title: "Figures Plotted"
author: "Zoe Dellaert"
date: "2025-11-05"
output:
  html_document: default
  github_document: default
---

Work in progress to have one doc for centralized figure work


```{r}
library(tidyverse)
library(purrr)
library(ggplot2)
library(patchwork)
library(stringr)
library(scales)
library(EnhancedVolcano)
library(ComplexHeatmap)
library(RColorBrewer)
library(circlize)
library(svglite)
library(cowplot)
library(magick)
```

## Setup

```{r}
#set standard output directory for figures
outdir <- "../output_RNA/differential_expression"

# Specify colors
ann_colors = list(Tissue = c(OralEpi = "#FD8D3C" ,Aboral = "mediumpurple1"))
```

### Load in Data

```{r}
vsd <- read.csv(paste0(outdir,"/vsd_expression_matrix.csv"))
vsd <- vsd %>% column_to_rownames(var = "X")

# Read in metadata 
meta <- read.csv("../data_RNA/LCM_RNA_metadata.csv") %>%
            dplyr::arrange(Sample) %>%
            mutate(across(c(Tissue, Fragment, Section_Date, LCM_Date), factor)) %>% 
            mutate(Sample_Desc = paste0(Fragment,"_",Tissue))

# Gene annotation data

CDSearch <- read.delim("../references/Pocillopora_acuta_HIv2.genes.Conserved_Domain_Search_results.txt", quote = "") %>% dplyr::rename("query" = X.Query)
EggNog <- read.delim("../references/Pocillopora_acuta_HIv2.genes.EggNog_results.txt") %>% dplyr::rename("query" = X.query)
DESeq_SwissProt <- read.csv(file=paste0(outdir,"/DESeq_SwissProt_annotation_categorized.csv"))

DE_05_marker_broc <- read.csv(file=paste0(outdir,"/DE_05_markergene_annotation.csv"))

```

## Figure 2

### Panel B: PCA

```{r}
pcaData <- read.csv(paste0(outdir, "/pcaData_allgenes.csv"), row.names = 1)
percentVar <- read.csv(paste0(outdir, "/pcaData_percentVar_allgenes.csv"))$percentVar
percentVar <- round(100 * percentVar)

PCA_small <- ggplot(pcaData, aes(PC1, PC2, color=Tissue)) +
  geom_point(size=2) +
  scale_color_manual(values = c("Aboral" = "mediumpurple1", "OralEpi" = "#FD8D3C"),
                     labels = c("Aboral" = "Aboral", "OralEpi" = "Oral"))+
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed() + theme_bw() + 
  theme(legend.position = c(0.8,0.25))

```


### Panel C

```{r}
ann_colors = list(Tissue = c(OralEpi = "#FD8D3C" ,Aboral = "mediumpurple1"))

colorRampPalette(c("mediumpurple1", "white", "#FD8D3C"))(5)

LFC_colors <- ifelse(DESeq_SwissProt$padj < 0.05 & DESeq_SwissProt$log2FoldChange > 1, '#FD8D3C',
                  ifelse(DESeq_SwissProt$padj < 0.05 & DESeq_SwissProt$log2FoldChange > 0 , '#FEC69D',
                         ifelse(DESeq_SwissProt$padj < 0.05 & DESeq_SwissProt$log2FoldChange < -1, '#AB82FF',
                                ifelse(DESeq_SwissProt$padj < 0.05 & DESeq_SwissProt$log2FoldChange < 0, '#D4C0FF',
                                       'grey'))))

LFC_colors[is.na(LFC_colors)] <- 'grey'
  names(LFC_colors)[LFC_colors == '#FD8D3C'] <- 'Up_Oral_LFC_sig'
  names(LFC_colors)[LFC_colors == '#FEC69D'] <- 'Up_Oral'
  names(LFC_colors)[LFC_colors == 'grey'] <- 'n.s.'
  names(LFC_colors)[LFC_colors == '#AB82FF'] <- 'Up_Aboral_LFC_sig'
  names(LFC_colors)[LFC_colors == '#D4C0FF'] <- 'Up_Aboral'
  
DESeq_SwissProt$Volcano_Label <-paste0(replace_na(stringr::str_wrap(DESeq_SwissProt$Heatmap_Label, width = 20), "Unannotated"),"\nLFC = ",round(DESeq_SwissProt$log2FoldChange,1))

top_DE_oral <- DESeq_SwissProt %>% filter(log2FoldChange > 1) %>% arrange(desc(log2FoldChange)) %>% head(5) %>% pull(query)
top_DE_aboral <- DESeq_SwissProt %>% filter(log2FoldChange < -1) %>% arrange(log2FoldChange) %>% head(5)  %>% pull(query)
label_top5 <- c(top_DE_oral,top_DE_aboral)

volcano <- EnhancedVolcano(DESeq_SwissProt, 
    lab = ifelse(DESeq_SwissProt$query %in% label_top5 , DESeq_SwissProt$Volcano_Label, ""),
    xlim = c(min(DESeq_SwissProt[["log2FoldChange"]], na.rm = TRUE) - 1.5, max(DESeq_SwissProt[["log2FoldChange"]], na.rm = TRUE) + 1.5),
  ylim = c(0, max(-log10(DESeq_SwissProt[["padj"]]), na.rm = TRUE) + .5),
    labSize = 3,
    axisLabSize = 12,
    captionLabSize = 4,
    x = "log2FoldChange", 
    y = "padj",
  shape=16,
    pCutoff = 0.05,
    colCustom = LFC_colors, colAlpha = .7,
    title = NULL, subtitle = NULL, caption = NULL,
    legendPosition = "none",
    legendLabSize = 8,
    pointSize = 1,
    legendIconSize = 3,
    drawConnectors = TRUE,
    lengthConnectors = unit(0.01, "npc"),
    directionConnectors = "both",
    border = 'full',
    max.overlaps = Inf,
    maxoverlapsConnectors = NULL,
    arrowheads =TRUE,
    min.segment.length = 0,
    gridlines.major = FALSE,
  gridlines.minor = FALSE,
  raster = TRUE
) #+ coord_flip() + scale_x_reverse()
 volcano
 
```

### Patchwork

```{r}
# Load images 
img_1A_crop <- ggdraw() + draw_image("images/1A_crop.png") 
img_1A_crop_cut <- ggdraw() + draw_image("images/1A_crop_cut.png")
  

top_row <- (free(img_1A_crop) + free(img_1A_crop_cut) + PCA_small) +
  plot_layout(widths = c(0.225, 0.225, 0.235)) 
final_fig <- 
  top_row / free(volcano) +
  plot_annotation(tag_levels = list(c("A1", "A2","B","C"))) &
  theme(plot.tag = element_text(size = 16, face = "bold"),
        plot.margin = margin(0.5,0.5,0.5,0.5),
        plot.tag.position  = c(.02, .9)) 

svglite("../output_RNA/differential_expression/composite_figs/Figure2.svg",
        width = 10, height = 7)
print(final_fig)
dev.off()
```

## Figure 4

```{r}
Biomin_all_expressed <- read.csv(paste0(outdir,"/DESeq_biomin_annotation.csv")) %>% left_join(DESeq_SwissProt %>% select(query,Heatmap_Label)) %>% select(-def_short)

write.csv(Biomin_all_expressed %>% select(-X) %>% select(Heatmap_Label,query,everything()), file=paste0(outdir,"/DESeq_biomin_annotation_heatmap_labels.csv"),row.names=FALSE)

Biomin_DE <- Biomin_all_expressed %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)
#choose the genes that will be plotted for the heatmap
select <- Biomin_DE$query

#gather expression info for those genes (assay(vsd) and get the z-scores)
z_scores <- t(scale(t(vsd[select, ])))
z_scores_df <- z_scores %>% as.data.frame() %>% rownames_to_column(var = "query")

Biomin_DE_Zscore <- Biomin_DE %>% left_join(z_scores_df) %>%
  rename_at(vars(meta$Sample),~ meta$Sample_Desc)

write.csv(Biomin_DE_Zscore%>% select(-X) %>% select(Heatmap_Label,query,everything()), file=paste0(outdir,"/DE05_biomin_zscore.csv"),row.names = FALSE)

# row annotations: Classification (type of biomin gene), category (genes i also called non-biomin), logfoldchange, padj
annotation_row <- Biomin_DE %>%
  select(query, Classification, log2FoldChange, padj) %>%
  tibble::column_to_rownames("query")

#row annotation: which genes are DE
annotation_row$DE <- abs(annotation_row$log2FoldChange) > 1 & annotation_row$padj < 0.05

# column annotations: tissue type
annotation_col_df <- meta %>% select(Tissue)

# colors
ann_colors = list(Tissue = c(OralEpi = "#FD8D3C" ,Aboral = "mediumpurple1"))
expr_colors <- colorRamp2(c(-2, 0, 2), c("#0571b0", "white", "#ca0020"))

Dark_Pal <- brewer.pal(length(unique(annotation_row$Classification))+2, "Dark2")

#remove purple and orange colors
Dark_Pal <- Dark_Pal[-c(2,3)]

class_colors <- setNames(
  Dark_Pal,
  unique(annotation_row$Classification)
)

# create row annotation object
row_ha <- rowAnnotation(
  Classification = annotation_row$Classification,
  col = list(
    Classification = class_colors
  ),
  annotation_name_gp = gpar(fontsize = 0, fontface = "bold"),
   annotation_legend_param = list(
    Classification = list(
      title = "Gene Classification",
      title_gp = gpar(fontsize = 10, fontface = "bold"),
      labels_gp = gpar(fontsize = 9)
    )
  ),
  width = unit(18, "mm"),
  gap = unit(1, "mm")
)

# column annotation object
col_ha <- HeatmapAnnotation(
  Tissue = annotation_col_df$Tissue,
  col = list(Tissue = ann_colors$Tissue),
  annotation_name_gp = gpar(fontsize = 0, fontface = "bold"),
  annotation_legend_param = list(
    Tissue = list(title = "Tissue", ncol = 1),
    title_gp = gpar(fontsize = 10, fontface = "bold"),
    labels_gp = gpar(fontsize = 9)
  ), height = unit(5, "mm"),
  gap = unit(1, "mm")
)

# labels
labels_all <- DESeq_SwissProt %>% 
  mutate(is_DE = abs(log2FoldChange) > 1 & padj < 0.05) %>%
  select(query, Heatmap_Label,is_DE) %>%
  mutate_all(~ ifelse(is.na(.), "", .)) #%>%
 # mutate(Heatmap_Label = ifelse(is_DE,Heatmap_Label, "")) #only label DE genes

row_labels <- labels_all$Heatmap_Label[match(rownames(z_scores), labels_all$query)]

# Perform hierarchical clustering on all samples and genes
row_hclust <- hclust(dist(z_scores))

# cut into 2 main clusters (oral vs aboral)
row_clusters <- cutree(row_hclust, k = 2)

# Combine expression-based grouping with supervised annotation
split_factor <- stringr::str_wrap(annotation_row$Classification, width = 18)
```

```{r}
ht <- Heatmap(
  z_scores,
  name = "Expression\nZ-score",
  cluster_rows = TRUE,
  cluster_columns = TRUE,
  show_parent_dend_line = FALSE,
  row_km = 2,
  row_split = split_factor,
  column_split = annotation_col_df$Tissue,
  col = expr_colors,
  row_gap = unit(c(1,1,1,1,2,1,1,1,1), "mm"),
  #row_gap = unit(2, "mm"),
  column_gap = unit(1.5, "mm"),
  left_annotation = row_ha,
  row_title = NULL,
  top_annotation = col_ha,
  show_row_names = TRUE,
  row_names_gp = gpar(fontsize = 6.25, fontface = "italic"),
  row_labels = row_labels,
  show_column_names = FALSE,
  column_dend_height = unit(5, "mm"),
  border = FALSE,
  column_title_gp = gpar(fontsize = 10, fontface = "bold"),
  heatmap_legend_param = list(
    title = "Expression\n(Z-Score)",
    title_gp = gpar(fontsize = 10, fontface = "bold"),
    labels_gp = gpar(fontsize = 9),
    legend_height = unit(3, "cm"),
    direction = "horizontal"
  ),
  rect_gp = gpar(col = "grey70", lwd = 0.5),
  use_raster = TRUE,
  raster_quality = 8,
  height = unit(6.25, "in")
)

svglite("../output_RNA/differential_expression/composite_figs/Figure4.svg", 
        width = 6, height = 8,
        system_fonts = list(sans = "Arial"))
draw(ht, merge_legend = TRUE, heatmap_legend_side = "bottom", annotation_legend_side = "bottom")
dev.off()
```



## Figure 5

```{r}
#get list of all differentially expressed marker genes
markers <- DE_05_marker_broc %>% select(query, Standardized_Name_spA) %>% distinct()

# get VST expression values
vsd_mat <- vsd %>% 
  tibble::rownames_to_column("gene")

# make VST expression value df into long format, and add marker info, filter to only keep expressed marker genes

mat_long <- vsd_mat %>%
  pivot_longer(-gene, names_to = "Sample", values_to = "vst") %>%
  left_join(meta %>% select(Sample, Tissue), by = "Sample") %>%
  left_join(markers, by = c("gene" = "query")) %>%
  filter(!is.na(Standardized_Name_spA))

# gene mean by tissue
plot_df <- mat_long %>%
  group_by(Standardized_Name_spA, gene, Tissue) %>%
  summarise(mean_vst = mean(vst, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(names_from = Tissue, values_from = mean_vst, values_fill = 0) %>%
  mutate(Standardized_Name_spA = str_to_title(str_replace_all(Standardized_Name_spA,"_","\n")))
```


```{r}
tissue_cols <- setdiff(colnames(plot_df), c("Standardized_Name_spA", "gene"))

# outer = OralEpi (t1), inner = Aboral (t2)
t1 <- tissue_cols[tissue_cols=="OralEpi"]
t2 <- tissue_cols[tissue_cols=="Aboral"]

# Sort sectors by tissue dominance for better visual flow
sector_totals <- plot_df %>%
  group_by(Standardized_Name_spA) %>%
  summarise(
    n_t1 = sum(.data[[t1]] > .data[[t2]], na.rm = TRUE),
    n_t2 = sum(.data[[t2]] > .data[[t1]], na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    dom_group = if_else(n_t1 > n_t2, "t1_dominant", "t2_dominant"),
    sort_value = if_else(dom_group == "t1_dominant", -n_t1, n_t2)  # negative makes n_t1 descending
  ) %>%
  arrange(
    factor(dom_group, levels = c("t1_dominant", "t2_dominant")),
    sort_value
  )

plot_df <- plot_df %>%
  mutate(Standardized_Name_spA = factor(Standardized_Name_spA, 
                                       levels = sector_totals$Standardized_Name_spA))


gene_counts <- table(plot_df$Standardized_Name_spA)
xlims <- cbind(rep(0, length(gene_counts)), as.numeric(gene_counts))
maxval <- max(c(plot_df[[t1]], plot_df[[t2]]), na.rm = TRUE)
maxval <- signif(maxval,0)
```


```{r}
#png("../output_RNA/differential_expression/DE_05_brocmarker_circ_colored.png", width = 3000, height = 3000, res = 300)
svglite("../output_RNA/differential_expression/composite_figs/Figure5.svg", width = 10, height = 10)

circos.clear()
circos.par(start.degree = 180,
           gap.after = setNames(c(rep(3,length(gene_counts)-1),8), names(gene_counts)),
           cell.padding = c(0.01, 0, 0.01, 0),
           canvas.xlim = c(-1, 1.1))
circos.initialize(factors = names(gene_counts), xlim = xlims)

# Sector labels with improved styling
circos.track(
  ylim = c(0, 1), 
  track.height = 0.08, 
  bg.border = NA,
  panel.fun = function(x, y) {
    sector <- CELL_META$sector.index
    # Calculate text size based on sector name length
    text_cex <- min(1.25, 30/nchar(sector))
    circos.text(CELL_META$xcenter, 1.85, sector,
                facing = "downward", 
                cex = text_cex,
                font = 2) 
  }
)

circos.trackPlotRegion(
  ylim = c(-maxval, maxval),  # negative to positive
  track.height = 0.5,
  bg.border = "gray90",
  panel.fun = function(x, y) {
    
    sector <- CELL_META$sector.index
    
    genes <- plot_df %>% filter(Standardized_Name_spA == sector) %>%
                      mutate(
              dom_group = if_else(.data[[t1]] > .data[[t2]], "t1_dominant", "t2_dominant")
            ) %>%
            arrange(
              factor(dom_group, levels = c("t1_dominant", "t2_dominant")),
              desc(if_else(dom_group == "t1_dominant", .data[[t1]], -.data[[t2]]))
            )

    # Add horizontal grid lines at standardized levels
    grid_levels <- c(maxval * -0.25, maxval * -0.5, maxval * -0.75, maxval * 0.25, maxval * 0.5, maxval * 0.75)
    for (level in grid_levels) {
      circos.lines(c(0, CELL_META$xlim[2]), c(level, level),
                   col = "gray90", lwd = 0.8)
    }
    
    for (i in seq_len(nrow(genes))) {
      t1_val <- genes[[t1]][i]
      t2_val <- genes[[t2]][i]
      
      # Determine colors based on dominance
      if (t1_val > t2_val) {
        t1_col <- "#FD8D3C"  # Bright color for dominant
        t2_col <- "#E6D3F7"  # Muted color for non-dominant
      } else {
        t1_col <- "#FED8A6"  # Muted color for non-dominant
        t2_col <- "mediumpurple1"  # Bright color for dominant
      }
      
      # Tissue 1 goes up (positive)
      circos.rect(i-1, 0, i, t1_val, col = t1_col, border = "white", lwd = 0.5)
      # Tissue 2 goes down (negative) 
      circos.rect(i-1, 0, i, -t2_val, col = t2_col, border = "white", lwd = 0.5)
    }
    
        # Add y-axis labels on top-most sector
    if (CELL_META$sector.numeric.index == 1) {
      circos.yaxis(side = "left", at = c(-maxval, -maxval/2, 0, maxval/2, maxval),
                   labels = c(sprintf("%.0f", -maxval), sprintf("%.0f", -maxval/2),"0", sprintf("%.0f", maxval/2), sprintf("%.0f", maxval)),labels.niceFacing = FALSE,
                   tick.length = 0.15, labels.cex = 0.8, lwd = 1)
    }
  }
)

# Enhanced legend with better positioning and styling
par(xpd = TRUE)
legend("center", 
       legend = paste(c("Outer:", "Inner:"), c(t1, t2)), 
       fill = c("#FD8D3C", "mediumpurple1"),
       border = "black",
       bty = "o",  # Draw box around legend
       cex = 1.0,
       title = "Tissue Type",
       title.cex = 1.1)
dev.off()
```


## Supplementary Tables

```{r}
library(openxlsx)

wb <- createWorkbook()

# Table S1
table_s1 <- read_csv("../data_RNA/Table_S1_LCM_RNA_metadata_bydissection.csv")
addWorksheet(wb, "Table S1")
writeData(wb, "Table S1", table_s1)

# Table S2
table_s2 <- read_csv("../output_RNA/differential_expression/DESeq_results.csv") %>% rename("query"=1)
addWorksheet(wb, "Table S2")
writeData(wb, "Table S2", table_s2)

# Table S3 (combined)
table_s3_aboral <- read_tsv("../output_RNA/differential_expression/semantic-enrichment/DE_05_Aboral_cluster_heatmap_Wang_wardD2.tsv") %>%
  rename_with(~gsub("^Aboral_", "", .)) %>%
  mutate(Tissue_Upregulation = "Aboral") %>%
  select(Tissue_Upregulation,everything())

table_s3_oral <- read_tsv("../output_RNA/differential_expression/semantic-enrichment/DE_05_Oral_cluster_heatmap_Wang_wardD2.tsv") %>% 
  rename_with(~gsub("^Oral_", "", .)) %>%
  mutate(Tissue_Upregulation = "Oral") %>%
  select(Tissue_Upregulation,everything())

table_s3 <- bind_rows(table_s3_aboral, table_s3_oral)
addWorksheet(wb, "Table S3")
writeData(wb, "Table S3", table_s3)

# Table S4 (combined)
table_s4_aboral <- read_tsv("../output_RNA/differential_expression/semantic-enrichment/MF_DE_05_Aboral_cluster_heatmap_Wang_wardD2.tsv") %>% 
  rename_with(~gsub("^Aboral_", "", .)) %>%
  mutate(Tissue_Upregulation = "Aboral") %>%
  select(Tissue_Upregulation,everything())
table_s4_oral <- read_tsv("../output_RNA/differential_expression/semantic-enrichment/MF_DE_05_Oral_cluster_heatmap_Wang_wardD2.tsv") %>% 
  rename_with(~gsub("^Oral_", "", .)) %>%
  mutate(Tissue_Upregulation = "Oral") %>%
  select(Tissue_Upregulation,everything())

table_s4 <- bind_rows(table_s4_aboral, table_s4_oral)
addWorksheet(wb, "Table S4")
writeData(wb, "Table S4", table_s4)

# Table S5 (combined)
table_s5_aboral <- read_tsv("../output_RNA/differential_expression/semantic-enrichment/CC_DE_05_Aboral_cluster_heatmap_Wang_wardD2.tsv") %>% 
  rename_with(~gsub("^Aboral_", "", .)) %>%
  mutate(Tissue_Upregulation = "Aboral") %>%
  select(Tissue_Upregulation,everything())
table_s5_oral <- read_tsv("../output_RNA/differential_expression/semantic-enrichment/CC_DE_05_Oral_cluster_heatmap_Wang_wardD2.tsv") %>% 
  rename_with(~gsub("^Oral_", "", .)) %>%
  mutate(Tissue_Upregulation = "Oral") %>%
  select(Tissue_Upregulation,everything())
table_s5 <- bind_rows(table_s5_aboral, table_s5_oral)
addWorksheet(wb, "Table S5")
writeData(wb, "Table S5", table_s5)

## Table S6
table_s6 <- read_csv("../output_RNA/differential_expression/DESeq_biomin_annotation_heatmap_labels.csv")
addWorksheet(wb, "Table S6")
writeData(wb, "Table S6", table_s6)

## Table S7
table_s7 <- read_csv("../output_RNA/differential_expression/DE05_biomin_zscore.csv")
addWorksheet(wb, "Table S7")
writeData(wb, "Table S7", table_s7)

## Table S8
table_s8 <- read_csv("../output_RNA/differential_expression/DESeq_markergene_annotation.csv") %>% select(-1) 
addWorksheet(wb, "Table S8")
writeData(wb, "Table S8", table_s8)

saveWorkbook(wb, "../Supplementary_Tables.xlsx", overwrite = TRUE)
```

